"""add name, description, likes, confirmations, denials, location_name to reports

Revision ID: 47662cf6e901
Revises: 98dba189ca10
Create Date: 2025-10-05 01:17:18.585821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47662cf6e901'
down_revision: Union[str, Sequence[str], None] = '98dba189ca10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('reports', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('confirmations', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('denials', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'denials')
    op.drop_column('reports', 'confirmations')
    op.drop_column('reports', 'likes')
    op.drop_column('reports', 'description')
    op.drop_column('reports', 'name')
    # ### end Alembic commands ###
