"""remove description from report

Revision ID: 7ad36dba8af1
Revises: b6b6d8987006
Create Date: 2025-10-04 21:35:46.744288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad36dba8af1'
down_revision: Union[str, Sequence[str], None] = 'b6b6d8987006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('description', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
