# api/Dockerfile
FROM python:3.13-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl ca-certificates libpq-dev \
 && rm -rf /var/lib/apt/lists/*

# uv (menedżer paczek)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_PROJECT_ENVIRONMENT=/opt/venv \
    PATH="/opt/venv/bin:$PATH"

WORKDIR /api


COPY pyproject.toml ./
COPY uv.lock ./
RUN uv venv && uv sync --frozen


CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","80"]